# 服务相关配置
server:
  address: ":8080"
  tplPath: "view" # 模板文件路径
  staticPrefix: "static" # 静态资源路由前缀
  staticPath: "public" # 静态资源目录
  staticSuffix: "png,jpg,jpeg,gif,mp4,css,js" # 静态资源文件支持的类型

# log日志配置
log:
  path: "logs"
  name: "log"
  model: "file" # console | file
  maxAge: 30 # 日志多少天后自动删除, 以天为单位

# mysql相关配置
mysql:
  default:
    link: "xxx:xxx@tcp(127.0.0.1:3306)/xxx?charset=utf8mb4&parseTime=true&loc=Local"
    debug: false #是否开启全局SQL打印
    createTime: "delete_time" #创建时间字段名
    updateTime: "update_time" #更新时间字段名
    deleteTime: "delete_time" #删除时间字段名
    maxOpen: 100 #最大打开连接数
    maxIdle: 50 #最大空闲连接数
    maxIdleTime: 0 #连接在空闲状态下的最大存活时间
    maxLifeTime: 0 #连接的最大生命周期，从创建到被关闭的总时间

# redis相关配置
redis:
  default:
    addr: "127.0.0.1:3679"
    password: ""
    db: 0 #索引
    poolSize: 100 #最大连接池

# 自定义额外的一些配置写下面
extra:
  jwtKey: "think-go"
  jwtExpiresAt: 30